CREATE TABLE `fleta_employee`.`employee` (
  `사번` VARCHAR(10) NOT NULL,
  `비밀번호` VARCHAR(100) NOT NULL DEFAULT '0000',
  `사진` VARCHAR(100),
  `이름` VARCHAR(10) NOT NULL,
  `입사년월일` DATETIME NOT NULL,
  `국적` VARCHAR(10) NOT NULL,
  `생년월일` DATETIME NOT NULL,
  `성별` VARCHAR(2) NOT NULL,
  `우편번호` VARCHAR(10),
  `주소` VARCHAR(50),
  `상세주소` VARCHAR(50),
  `전화번호` VARCHAR(20),
  `휴대폰번호` VARCHAR(20),
  `이메일` VARCHAR(50),
  `부서` VARCHAR(20) NOT NULL,
  `직급` VARCHAR(10) NOT NULL,
  `직종` VARCHAR(20) NOT NULL,
  `퇴사년월일` DATETIME,
  `급여이체은행` VARCHAR(10),
  `계좌번호` VARCHAR(20),
  `예금주` VARCHAR(10),
  `비고` VARCHAR(1000),
  `등급` VARCHAR(10) NOT NULL DEFAULT '사용자',
  PRIMARY KEY (`사번`),
  UNIQUE INDEX `사번_UNIQUE` (`사번` ASC) VISIBLE);
